version: "3"

services:
  web:
    image: sornchaithedev/ku-clubs:sha-099eb17
    ports:
      - "3000:3000"
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3001:80
    environment:
      - PMA_ARBITRARY=1
